on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

name: CI

jobs:

  php-tests:
    env:
      ENV_INTERACTIVE: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.3', '8.4' ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run tests
        run: make ga-run-tests
