on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

name: CI

jobs:

  php-tests:
    env:
      ENV_INTERACTIVE: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.0', '8.1' ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Run tests
        run: make ga-run-tests

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
